name: eq_request
description: Emergency Quota Request Generator for Indian Railways

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # PDF Generation & Viewing
  pdf: ^3.10.7
  printing: ^5.12.0
  syncfusion_flutter_pdfviewer: ^26.1.40   # 👈 Naya Package Zoom ke liye add kiya hai

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # HTTP for PNR API
  http: ^1.1.0

  # Date Picker
  intl: ^0.18.1

  # Share
  share_plus: ^10.0.0

  # Path
  path_provider: ^2.1.1

  # Flutter SVG
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1   # App Icon Package Add Kiya Hai

flutter:
  uses-material-design: true

  assets:
    - assets/images/indian_railway.png
    - assets/images/stamp_round.png
    - assets/images/ekbharat_logo.png
    - assets/images/ashoka.svg
    - assets/images/signature.png
    - assets/images/signature_text.png
    - assets/images/app_icon.png      # Custom App Icon ko assets me bhi add kar diya

# 👇 App Icon Configuration 👇
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
